---
- hosts: dev
  vars:
    os_environment:
      - key: API_KEY_FINAL
        value : "{{ lookup('env', 'RIOT_GAMES_API') }}"
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: yes
      become: true

    - name: populate /etc/environment
      lineinfile:

        path: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value}}"

      with_items: "{{ os_environment }}"
      become: yes
    
    - name: install docker
      ansible.builtin.yum:
        name: docker
        state: present
        update_cache: yes
      become: true

    - name: install docker-compose
      ansible.builtin.pip:
        name: docker-compose
        state: present
        update_cache: yes
      become: true
    
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/TreyDegale/riotGames.git
        dest: ~/riotGames
        clone: yes
        update: yes

    - name: docker-compose build
      shell: "docker-compose build"
      become: true

    - name: docker-compose up
      shell: "docker-compose up -d"
      become: true

    # - name: docker build
    #   shell: "docker run -e API_KEY={{ API_KEY }} -p 8080:8080 -d riotgames:dev"
    #   become: true