---
- hosts: dev
  vars:
    sshkey: "/home/ec2-user/.ssh/authorized_keys"
    API_KEY: lookup('env', RIOT_GAMES_API)
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: yes
      become: true
    
    - name: install docker
      ansible.builtin.yum:
        name: docker
        state: present
        update_cache: yes
      become: true
    
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/TreyDegale/riotGames.git
        dest: ~/riotGames
        clone: yes

    - name: docker build
      shell: "docker run -e API_KEY={{ API_KEY }} -p 8080:8080 -d riotgames:dev"
      become: true