---
- hosts: dev
  vars:
    sshkey: "/home/ec2-user/.ssh/authorized_keys"
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: yes
      become: true
    
    - name: install docker
      ansible.builtin.yum:
        name: docker
        state: present
        update_cache: yes
      become: true
    
    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/TreyDegale/riotGames.git
        dest: ~/riotGames
        clone: yes

    - name: docker run
      shell: "docker run -e RIOT_GAMES_API= {{ lookup('env', RIOT_GAMES_API) }} -p 8080:8080 -d riotgames:dev"
      become: true