---
- hosts: dev
  vars:
   # environment variable vars
    os_environment:
      - key: API_KEY_FINAL
        value : "{{ lookup('env', 'RIOT_GAMES_API') }}"
  tasks:
    # environment variable task
    - name: populate /etc/environment
      lineinfile:

        path: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value}}"

      with_items: "{{ os_environment }}"
      become: yes
    
    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/TreyDegale/riotGames.git
        dest: ~/riotGames-ec2-final-steps
        version: ec2-final-steps
        clone: yes
        update: yes

    - name: docker-compose build
      community.docker.docker_compose:
        project_src: ~/riotGames-ec2-final-steps
        build: yes

    - name: docker-compose up
      community.docker.docker_compose:
        project_src: ~/riotGames-ec2-final-steps
        state: present