---
- hosts: dev
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: yes
      become: true
    
    - name: install docker
      ansible.builtin.yum:
        name: docker
        state: present
        update_cache: yes
      become: true

    - name: install docker-compose
      ansible.builtin.pip:
        name: docker-compose
        state: present
        update_cache: yes
      become: true

    - name: install gunicorn
      ansible.builtin.pip:
        name: gunicorn
        state: present
        update_cache: yes
      become: true